version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - carford-town
    ports:
      - 5440:5432
    volumes:
      - BD_postgres:/var/lib/postgresql
    environment:
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=carford
  
  flask-server:
    container_name: flask-server
    image: carford
    networks:
      - carford-town
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://<user>:<password>@postgres:5432/carford
      - JWT_SECRET=
      - PORT=3000
      - TEST_USER_USERNAME=<user>
      - TEST_USER_PASSWORD=<password>
    depends_on:
      - postgres
      
volumes:
 BD_postgres:

networks:
  carford-town: